FROM node:14.16.0-alpine3.11 AS build

WORKDIR /opt/app-root

COPY package*.json ./

RUN npm install

ADD . .

RUN npm run build

FROM node:14.16.0-alpine3.11 as production

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/app-root

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=build /opt/app-root/dist ./dist

EXPOSE 3333

CMD ["node", "dist/main"]